name: CI

on:
  push:
    branches: [main, 'feature/*']
  pull_request:
    branches: [main, 'feature/*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint || echo 'Lint warnings only'
      - name: Run tests
        run: npm test
      - name: Build (se aplicável)
        run: |
          if [ -f package.json ] && grep -q 'build' package.json; then npm run build; else echo 'No build step'; fi
      - name: Upload coverage
        if: success()
        run: |
          if [ -d coverage ]; then echo "Cobertura gerada"; fi
        shell: bash 